### ISSUE TITLE
only 50 channels

### ISSUE THREAD

**Issue by ArneBab** [4hiziri/rocket-chat#1]
In our instance rocket-chat only shows the first 50 channels, missing many I need. It would be nice to access rocket chat without its web interface, but this currently blocks that.

**Comment by 4hiziri** [comment]
I think this bug was fixed by commit ~~7e4aee9fe84cfddaa56a4a58814736ec6cfb849b.~~
Sorry, 2494f867c170caecde0be6b50afb5a00d0e22a1a is fine.
Thanks for letting me know.

**Comment by ArneBab** [comment]
Thank you very much!

With the most recent version I get

    Debugger entered--Lisp error: (void-variable url)
      statistics([cl-struct-auth-token "XXXX" "XXXXX"])

with

    (defun statistics (auth-token &optional refresh)

**Comment by 4hiziri** [comment]
It seems like I edited wrong code.
14116792aac4a9670072d7c3a4ec70c06aab12cf When I tested, this worked.
I hope it goes well next.

**Comment by ArneBab** [comment]
Now emacs connects to /api/v1/statistics, but I see the error REQUEST [error] Error (error) while connecting to HOST/api/v1/statistics

edebug gives me

```
REQUEST [error] Error (error) while connecting to HOST/api/v1/statistics.
Result: #1=[cl-struct-request-response 400 nil ((success . :json-false) (error . "Not allowed [error-not-allowed]") (errorType . "error-not-allowed")) (error http 400) error "HOST/api/v1/statistics?refresh=true" t (:params (("refresh" . "true")) :parser json-read :headers (("X-Auth-Token" . "TOKEN") ("X-User-Id" . "USERID")) :success (lambda (&rest --cl-rest--) "\n\n(fn &key DATA &allow-other-keys)" (let* ((data (car (cdr (plist-member --cl-rest-- (quote :data)))))) (setq ret data))) :timeout 3 :sync t :error #[128 "\302\300\303\301\"\"\207" [request-default-error-callback ("HOST/api/v1/statistics") apply append] 6 "\n\n(fn &rest ARGS2)"] :url "HOST/api/v1/statistics?refresh=true" :response #1#) #<killed buffer> "HTTP/1.1 400 Bad Request\nDate: Mon, 10 Sep 2018 07:47:13 GMT\nServer: Apache/2.4.25 (Debian)\nAccess-Control-Allow-Origin: *\nX-Instance-ID: ahKc8Ps2ZtaXjY8Gq\nCache-Control: no-store\nPragma: no-cache\ncontent-type: application/json\nVary: Accept-Encoding\nContent-Encoding: gzip\nConnection: close\nTransfer-Encoding: chunked\n" [nil 23446 8580 140672 nil request-response--timeout-callback (#1#) nil 808000] curl nil]
```

In the later channel.list request, I then see

```
cl-struct-request-response 200 nil ((channels .... ) (count . 50) (offset . 0) (total . 173) (success . t))
```

**Comment by 4hiziri** [comment]
It seems server doesn't allow some APIs.
I'll add load-channel-num option and channel load menu.
It will take several days, sorry :(

**Comment by ArneBab** [comment]
No problem — thank you *very very much* for taking this up!

Navigating the Rocket.Chat web interface to write someone takes at least 10s, and aside from doing that many times every day (so it easily sums up to several minutes), it completely disrupts my flow. Judging from my first tests this should be a snap in your mode.

**Comment by 4hiziri** [comment]
This plugin is still immature and unstable, so it is comfortable for you to use Rocket.chat web interface.

Anyway, I have fixed this bug by adding additional channel load function.
Thank you for reporting.

**Comment by ArneBab** [comment]
I can now see more channels (including the ones I need), but the request works only once, so there are still some channels I cannot get shown.

Please do not let this stress you: I am testing your plugin and using it where it already works well. I still have the web interface as backup for the things which do not work yet.

**Comment by 4hiziri** [comment]
The server limits the number of channels that users get, so this plugin wasn't able to get all channels.
I have fixed this problem by sending multiple requests to the server.
Please try latest version.

**Comment by ArneBab** [comment]
It works now! Thank you!

**Comment by 4hiziri** [comment]
I'm glad to hear that! :)
